id: csharp-dotnet-development
name: C# .NET Development 
description: Essential prompts, instructions, and chat modes for C# and .NET development including testing, documentation, and best practices.
tags: [csharp, dotnet, aspnet, testing]
items:
  - path: prompts/csharp-async.prompt.md
    kind: prompt
  - path: prompts/aspnet-minimal-api-openapi.prompt.md
    kind: prompt
  - path: instructions/csharp.instructions.md
    kind: instruction
  - path: instructions/dotnet-architecture-good-practices.instructions.md
    kind: instruction
  - path: chatmodes/expert-dotnet-software-engineer.chatmode.md
    kind: chat-mode
  - path: prompts/csharp-xunit.prompt.md
    kind: prompt
  - path: prompts/dotnet-best-practices.prompt.md
    kind: prompt
display:
  ordering: alpha
  show_badge: false