id: database-data-management
name: Database & Data Management
description: Database administration, SQL optimization, and data management tools for PostgreSQL, SQL Server, and general database development best practices.
tags: [database, sql, postgresql, sql-server, dba, optimization, queries, data-management]
items:
  # Database Expert Chat Modes
  - path: chatmodes/postgresql-dba.chatmode.md
    kind: chat-mode
  - path: chatmodes/ms-sql-dba.chatmode.md
    kind: chat-mode

  # Database Instructions
  - path: instructions/ms-sql-dba.instructions.md
    kind: instruction
  - path: instructions/sql-sp-generation.instructions.md
    kind: instruction

  # Database Optimization Prompts
  - path: prompts/sql-optimization.prompt.md
    kind: prompt
  - path: prompts/sql-code-review.prompt.md
    kind: prompt
  - path: prompts/postgresql-optimization.prompt.md
    kind: prompt
  - path: prompts/postgresql-code-review.prompt.md
    kind: prompt

display:
  ordering: alpha
  show_badge: true
