id: devops-oncall
name: DevOps On-Call
description: A focused set of prompts, instructions, and a chat mode to help triage incidents and respond quickly with DevOps tools and Azure resources.
tags: [devops, incident-response, oncall, azure]
items:
  - path: prompts/azure-resource-health-diagnose.prompt.md
    kind: prompt
  - path: instructions/devops-core-principles.instructions.md
    kind: instruction
  - path: instructions/containerization-docker-best-practices.instructions.md
    kind: instruction
  - path: chatmodes/azure-principal-architect.chatmode.md
    kind: chat-mode
  - path: prompts/multi-stage-dockerfile.prompt.md
    kind: prompt
display:
  ordering: manual
  show_badge: true