id: java-development
name: Java Development
description: Comprehensive collection of prompts and instructions for Java development including Spring Boot, Quarkus, testing, documentation, and best practices.
tags: [java, springboot, quarkus, jpa, junit, javadoc]
items:
  - path: instructions/java.instructions.md
    kind: instruction
  - path: instructions/springboot.instructions.md
    kind: instruction
  - path: instructions/quarkus.instructions.md
    kind: instruction
  - path: instructions/quarkus-mcp-server-sse.instructions.md
    kind: instruction
  - path: instructions/convert-jpa-to-spring-data-cosmos.instructions.md
    kind: instruction
  - path: instructions/java-11-to-java-17-upgrade.instructions.md
    kind: instruction
  - path: instructions/java-17-to-java-21-upgrade.instructions.md
    kind: instruction
  - path: instructions/java-21-to-java-25-upgrade.instructions.md
    kind: instruction
  - path: prompts/java-docs.prompt.md
    kind: prompt
  - path: prompts/java-junit.prompt.md
    kind: prompt
  - path: prompts/java-springboot.prompt.md
    kind: prompt
  - path: prompts/create-spring-boot-java-project.prompt.md
    kind: prompt
display:
  ordering: alpha
  show_badge: false
