id: power-apps-code-apps
name: Power Apps Code Apps Development
description: Complete toolkit for Power Apps Code Apps development including project scaffolding, development standards, and expert guidance for building code-first applications with Power Platform integration.
tags: [power-apps, power-platform, typescript, react, code-apps, dataverse, connectors]
items:
  # Power Apps Code Apps Prompt
  - path: prompts/power-apps-code-app-scaffold.prompt.md
    kind: prompt

  # Power Apps Code Apps Instructions
  - path: instructions/power-apps-code-apps.instructions.md
    kind: instruction

  # Power Platform Expert Chat Mode
  - path: chatmodes/power-platform-expert.chatmode.md
    kind: chat-mode

display:
  ordering: manual
  show_badge: true
