id: power-platform-mcp-connector-development
name: Power Platform MCP Connector Development
description: Complete toolkit for developing Power Platform custom connectors with Model Context Protocol integration for Microsoft Copilot Studio
tags: 
  - power-platform
  - mcp
  - copilot-studio
  - custom-connector
  - json-rpc
items:
  - path: instructions/power-platform-mcp-development.instructions.md
    kind: instruction
  - path: prompts/power-platform-mcp-connector-suite.prompt.md
    kind: prompt
  - path: prompts/mcp-copilot-studio-server-generator.prompt.md
    kind: prompt
  - path: chatmodes/power-platform-mcp-integration-expert.chatmode.md
    kind: chat-mode
display:
  ordering: manual
  show_badge: true