id: technical-spike
name: Technical Spike
description: Tools for creation, management and research of technical spikes to reduce unknowns and assumptions before proceeding to specification and implementation of solutions.
tags: [technical-spike, assumption-testing, validation, research]
items:
  # Planning Chat Modes
  - path: chatmodes/research-technical-spike.chatmode.md
    kind: chat-mode

  # Planning Prompts
  - path: prompts/create-technical-spike.prompt.md
    kind: prompt
display:
  ordering: alpha # or "manual" to preserve the order above
  show_badge: false # set to true to show collection badge on items
